export const INFOBOX_ARROW = '.___tour-guide-infobox-arrow'
export const INFOBOX_BUTTON_PRIMARY = '.___tour-guide-infobox-button-primary'
export const INFOBOX_BUTTON_SECONDARY = '.___tour-guide-infobox-button-secondary'
export const INFOBOX_ACTION_BUTTON = '.___tour-guide-infobox-button-action'
export const INFOBOX_CARD = '.___tour-guide-infobox-card'
export const INFOBOX_DESCRIPTION = '.___tour-guide-infobox-description'
export const INFOBOX_DESCRIPTION_WRAPPER = '.___tour-guide-infobox-description-wrapper'
export const INFOBOX_FOOTER = '.___tour-guide-infobox-footer'
export const INFOBOX_WRAPPER = '.___tour-guide-infobox-wrapper'
export const INFOBOX_MAIN = '.___tour-guide-infobox-main'
export const INFOBOX_IMAGE_WRAPPER = '.___tour-guide-infobox-image-wrapper'
export const INFOBOX_IMAGE = '.___tour-guide-infobox-image'
export const INFOBOX_COUNTER = '.___tour-guide-infobox-counter'
export const BLUE_THEME_WRAPPER = '.___tour-guide-blue-theme'

export const SHIM = '.___tour-guide-shim'
export const SHIM_HOLE = '.___tour-guide-shim-hole'
export const SHIM_HOLE_BORDER_TL = '.___tour-guide-shim-hole-border-tl'
export const SHIM_HOLE_BORDER_TR = '.___tour-guide-shim-hole-border-tr'
export const SHIM_HOLE_BORDER_BL = '.___tour-guide-shim-hole-border-bl'
export const SHIM_HOLE_BORDER_BR = '.___tour-guide-shim-hole-border-br'

export const TINKERBELL = '.___tour-guide-tinkerbell'
export const TINKERBELL_CIRCLE = '.___tour-guide-tinkerbell-circle'
export const TINKERBELL_CIRCLE_ANIMATED = '.___tour-guide-tinkerbell-circle-animated'
